/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jbudget;

import it.unicam.cs.pa.jbudget.javaFX.JavaFXJBudget;
import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        launchGui();
    }

    private static void launchGui() {
        Application.launch(JavaFXJBudget.class);
    }
}
